### ISSUE TITLE
support PNG

### ISSUE THREAD

**Issue by sandyaiotsoft** [waschinski/photo-stream#28]
Hi, what can I do to make the project support PNG, thanks！

**Comment by waschinski** [comment]
Hi, I was discussing this with @boerniee today and we are considering moving away from using Exifr which can only handle JPEG and TIFF images. I am currently playing around with a Ruby wrapper for ExifTool and it looks quite promising! I will keep you updated.

**Comment by timdonovanuk** [comment]
Big ask I appreciate, but video support would also be amazing. This is less out of scope than you'd think, what with iPhone live photo formats (HEIC/HEVC, which are basically jpeg + mov files).

**Comment by waschinski** [comment]
@timdonovanuk I am afraid it might be harder to implement videos than you think. :) While the library processing the images (libvips) does indeed support HEIC it still is a library for processing images only. Also since browsers are not able to display HEIC images you would have to convert HEIC videos to some other format. Right now I even struggle to get the convert function working so HEIC images get converted to JPEG. It just seems to ignore it when I set it in the config file.

**Comment by waschinski** [comment]
PNG support will be coming along with WebP support #68
