### ISSUE TITLE
Additional Gems

### ISSUE THREAD

**Issue by ydreN** [waschinski/photo-stream#3]
Thank you for continuing this. I wanted to add this in case it saves someone else some time.
I'm testing with:
`ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]`
`jekyll 4.2.0`
To be able to use `bundle exec jekyll serve` I had to add `gem "webrick", "~> 1.7"` to the Gemfile and to get it to read the /.env file I had to add `gem "jekyll-dotenv"`

Then added 
` -jekyll-dotenv` under the plugins section of the _config.yml

Going to see if there is a way to randomize the photo names. So far I've just been running a script to do it before copying them into the folder

**Comment by waschinski** [comment]
Sorry for the late reply, I was actually expecting to get notified by new issues in this repo. :|

I must admit I am pretty new to Ruby and was mainly focusing on getting photo stream to run in a Docker container. So I simply went with a ruby 2.7.3 image in the Dockerfile and tried to get rid of all the log spam that occured first.

As you just found out the hard way, this means the project basically isn't ready for Ruby 3.0 yet. Sorry for that. :/ Glad to see you still got it running. And many thanks for sharing how! 

`Webrick` obviously used to ship with Ruby but no longer does with Ruby 3.0 so that's why the gem has to be added now.

I was looking into [`jekyll-dotenv`](https://0xacab.org/sutty/jekyll/jekyll-dotenv) but it seems to basically do the same as [`jekyll-environment-variables`](https://github.com/iBug/jekyll-environment-variables). I wonder why it didn't work with the latter. But `jekyll-dotenv` seems to allow creating hashes from environment variables (so  `AUTHOR.NAME` instead of `AUTHOR_NAME` would be possible) so it might be worth to go with it in the future.

**Comment by waschinski** [comment]
I just released a new version containing your fixes. Thank you very much!

> Going to see if there is a way to randomize the photo names. So far I've just been running a script to do it before copying them into the folder

May I ask why you do randomize the photo names?

**Comment by ydreN** [comment]
> I just released a new version containing your fixes. Thank you very much!
> 
> > Going to see if there is a way to randomize the photo names. So far I've just been running a script to do it before copying them into the folder
> 
> May I ask why you do randomize the photo names?

No problem, I'm new to Ruby as well. 
Mainly just personal preference I'd rather have each picture as a unique url than the name the camera puts out. I can rename during export but it'll be more efficient for me as part of the build process

**Comment by waschinski** [comment]
> > May I ask why you do randomize the photo names?
> 
> Mainly just personal preference I'd rather have each picture as a unique url than the name the camera puts out. I can rename during export but it'll be more efficient for me as part of the build process

I see, but to me that actually sounds like a job for a shell script though which is what you are already doing.

I could try reworking the scripts in the `_script` folder and make a single one that accepts options. So instead of calling `sh ./_script/build-n-lftp.sh` you could call something like `sh ./_script/build.sh --lftp --rand`. Feel free to open a seperate issue for this if it sounds like a good idea to you. ;)
