### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by maddingamer** [waschinski/photo-stream#37]
Hi again,

is it possible to define on how to sort the images? E.g. by recording date?
Furthermore, how can I change the favicon when using docker-compose image?

Thanks! :)

**Comment by oliverhihn** [comment]
You should be able to copy your own favicon file into the running container using the `docker cp` command. Maybe you have to restart the container afterwards. Just be sure to clear your browser cache when testing if it worked, since the old favicon will still be displayed from cache. Or just testing with an incognito window should work aswell.

**Comment by waschinski** [comment]
> is it possible to define on how to sort the images? E.g. by recording date?

Photos are being sorted by exif data (date_time_original) or as a fallback the photos file modified_time. So while it is not possible to define a different sorting right now, it should be sorting by recording date, more or less.
